#!/usr/bin/env sh
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc" 2>/dev/null
[ -f "$HOME/.bash_profile" ] && . "$HOME/.bash_profile" 2>/dev/null
export PATH="$PATH:/c/Program Files/nodejs:${HOME}/scoop/apps/nodejs/current/bin:${HOME}/scoop/apps/node/current/bin:${APPDATA}/npm"
npm run build
npm run lint:check
