#!/usr/bin/env sh
# Desabilitado - reative descomentando abaixo
exit 0
# [ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc" 2>/dev/null
# export PATH="$PATH:/c/Program Files/nodejs:${HOME}/scoop/apps/nodejs/current/bin:${APPDATA}/npm"
# npm run build
# npm run lint:check
